# Generated by Django 4.0.4 on 2022-06-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='mailid@gmail.com', max_length=50),
        ),
    ]
