# Generated by Django 4.0 on 2021-12-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='', max_length=100)),
                ('video_link', models.CharField(max_length=100)),
                ('video_id', models.PositiveIntegerField()),
                ('video_category', models.CharField(max_length=50)),
                ('video_price', models.IntegerField(default=0)),
                ('video_rating', models.FloatField(default=0.0)),
                ('video_releasedate', models.DateTimeField()),
                ('video_description', models.TextField(max_length=500)),
                ('video_views', models.IntegerField()),
                ('video_discount', models.IntegerField()),
                ('video_thumbnail', models.ImageField(upload_to='videos/thumbnail/')),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_verified', models.BooleanField(default=False)),
                ('purchased_videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.purchased')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='purchased',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.video'),
        ),
    ]
