# Generated by Django 4.0.4 on 2022-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_video_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.TextField(default=1.1),
        ),
    ]
